### ISSUE TITLE
windows mock server 报 prereload faild

### ISSUE THREAD

**Issue by eczn** [matmanjs/matman#116]
![image](https://user-images.githubusercontent.com/13131724/42300975-91ae2626-8045-11e8-871b-210550f6eac0.png)

相关代码

![image](https://user-images.githubusercontent.com/13131724/42300997-b2566064-8045-11e8-8ada-279d56e0c7d0.png)

**Comment by helinjiang** [comment]
错误原因是正则匹配路径时未兼容 windows，稍后修复

**Comment by helinjiang** [comment]
已修复，请升级 `matman-e2e` 版本到 `v3.0.9` 及以上，同时，在 `matman.config.js` 中的 `clientScriptMatch` 值修改为 `/crawlers[\/|\\].*\.js$/` 。

> `matman.config.js` 中的 `clientScriptMatch` 默认值就是 `/crawlers[\/|\\].*\.js$/` ，因此你可以不必人工设置
