### ISSUE TITLE
windows 下目录文件命名有误

### ISSUE THREAD

**Issue by eczn** [matmanjs/matman#117]
![image](https://user-images.githubusercontent.com/13131724/42301586-d07c28e6-8048-11e8-9d59-c9f4c17370b1.png)

**Comment by helinjiang** [comment]
在 windows 中路径替换时有问题，未意识到 windows 中的 `\` 而不是 '/'。稍后将进行修复


https://gist.github.com/helinjiang/640b365ed377bef99b8a9c41f7337257

**Comment by helinjiang** [comment]
已修复，请升级 `matman-e2e` 版本到 `v3.0.9` 及以上
