### ISSUE TITLE
webstorm 里面的代码提示

### ISSUE THREAD

**Issue by helinjiang** [matmanjs/matman#181]
https://www.jetbrains.com/help/webstorm/configuring-javascript-libraries.html#ws_js_custom_third_party_library

在 wbestorm 里面没有代码提示，开发体验不友好

![image](https://user-images.githubusercontent.com/13464168/82400584-46127300-9a8a-11ea-9e59-f5d0b47d871e.png)

**Comment by wangjq4214** [comment]
已经实现
