### ISSUE TITLE
matman-cli build问题

### ISSUE THREAD

**Issue by wangjq4214** [matmanjs/matman#185]
## For BUG

1. 在执行matman build --dev 之后生成的文件不能将getPageInfo函数正确的挂载在window对象上
2. 将生成的文件复制到控制台执行，100%复现
![image](https://user-images.githubusercontent.com/35188480/82518039-019dda80-9b51-11ea-8d1e-0cc064a051d5.png)

**Comment by helinjiang** [comment]
已解决，升级 matman 到 5.0.7 及以上版本即可
