### ISSUE TITLE
导航之后 puppeteer 上下文被销毁导致报错

### ISSUE THREAD

**Issue by wangjq4214** [matmanjs/matman#201]
## For BUG

导航之后 puppeteer 上下文被销毁导致报错

**Comment by damonare** [comment]
![截屏2020-07-13 下午8 52 08](https://user-images.githubusercontent.com/15198148/87306556-c2857780-c54a-11ea-9cbc-2798ad5f522f.png)

**Comment by damonare** [comment]
Error: Execution context was destroyed, most likely because of a navigation.

**Comment by helinjiang** [comment]
https://github.com/puppeteer/puppeteer/issues/3323
