### ISSUE TITLE
MatmanResult.isExistJSBridge方法测试url不通过

### ISSUE THREAD

**Issue by xzlgh** [matmanjs/matman#206]
## For BUG
MatmanResult.isExistJSBridge方法检测url是否存在时，期望得到的结果是url是存在的，实际测试用例测试结果显示检测不存在，获取到MatmanResult对象resultData，`resultData.globalInfo.recorder`里面存在`tapp://oepnpage/a?id=1234`，调用isExistJSBridge方法，返回结果false。
#### 环境
matman： v6.0.5
matman-cli：v6.0.5
mocha: v8.0.1

## For question

测试用例类似于如下情况：
```js
describe('第二步：检查桥接', () => {
        it('实际调用 tapp://oepnpage/a?id=1234', () => {
             const url = 'tapp://oepnpage/a?id=1234';
             expect(resultData.isExistJSBridge(url)).to.be.true;
        });
});
```
测试结果：false
期望结果：true

检查matman/build/matman-result-output/目录下对应的json文件，在里面搜索`tapp://oepnpage/a?id=1234`，能搜索到。
此时，检查结果不应该出现false。

**Comment by wangjq4214** [comment]
已经修复 即将发布

**Comment by wangjq4214** [comment]
已经通过console方法进行暂时修复，请 [查看](https://matmanjs.github.io/matman/api/matman-result.html#_2-11-isexistjsbridge)
